// <auto-generated />
namespace RitterToDo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Starter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Starter));
        
        string IMigrationMetadata.Id
        {
            get { return "Starter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
